name: "reverse_experiment"

data:
    src: "src"
    trg: "trg"
    train: "test/data/reverse/train"
    dev: "test/data/reverse/dev"
    test: "test/data/reverse/test"
    level: "word"
    lowercase: False
    max_sent_length: 11
    voc_min_freq: 0
    voc_limit: 100
    #src_vocab: "my_model/src_vocab.txt"
    #trg_vocab: "my_model/trg_vocab.txt"

testing:
    beam_size: 1
    alpha: 1.0

training:
    #load_model: "my_model/3300.params"
    random_seed: 42
    optimizer: "adam"
    loss: "crossentropy"
    learning_rate: 0.0002
    learning_rate_min: 0.0002
#    clip_grad_val: 1.0
    weight_decay: 0.0
    clip_grad_norm: 1.0
    batch_size: 10
    scheduling: "plateau"
    patience: 5
    decrease_factor: 0.5
    schedule_after_loss: True
    epochs: 30
    validation_freq: 1000
    logging_freq: 100
    eval_metric: "bleu"
    model_dir: "transformer_reverse_001"
    overwrite: True
    shuffle: True
    use_cuda: False
    max_output_length: 11
    print_valid_sents: 3

model:
    initializer: "xavier"
    embed_initializer: "xavier"
    embed_init_weight: 0.1
    bias_initializer: "zeros"
    encoder:
        type: "transformer"
        num_layers: 2
        num_heads: 8
        embeddings:
            embedding_dim: 128
            scale: True
        hidden_size: 128
        ff_size: 256
        dropout: 0.1
    decoder:
        type: "transformer"
        num_layers: 2
        num_heads: 8
        embeddings:
            embedding_dim: 128
            scale: True
        hidden_size: 128
        ff_size: 256
        dropout: 0.1
