name: "reverse_experiment"

data:
    src: "de"
    trg: "en"
    train: "test/data/iwslt14/train.bpe.32000"
    dev: "test/data/iwslt14/valid.bpe.32000"
    test: "test/data/iwslt14/test.bpe.32000"
    level: "bpe"
    lowercase: True
    max_sent_length: 62
    voc_min_freq: 1
#    voc_limit: 32000

testing:
    beam_size: 1
    alpha: 1.0

training:
    #load_model: "my_model/3300.params"
    random_seed: 42
    optimizer: "adam"
    adam_betas: [0.9, 0.98]
    scheduling: "noam"
    schedule_after_loss: True
    loss: "crossentropy"
    learning_rate: 0.0
    learning_rate_min: 0.00000001
#    clip_grad_val: 1.0
    weight_decay: 0.0
    clip_grad_norm: 1.0
    batch_size: 80
    patience: 5
    decrease_factor: 0.5
    epochs: 100
    validation_freq: 2000
    logging_freq: 500
    eval_metric: "bleu"
    model_dir: "transformer_iwslt_deen_bahdanau_big_8l_02"
    overwrite: True
    shuffle: True
    use_cuda: True
    max_output_length: 100
    print_valid_sents: [1, 2, 3]

model:
    initializer: "xavier"
    # embedding init matters a lot! should investigate
    embed_initializer: "normal"
    embed_init_weight: 0.05
    bias_initializer: "zeros"
    encoder:
        type: "transformer"
        num_layers: 8
        num_heads: 8
        embeddings:
            embedding_dim: 512
            scale: True
        # typically ff_size = 4 x hidden_size
        hidden_size: 512
        ff_size: 2048
        dropout: 0.3
    decoder:
        type: "transformer"
        num_layers: 8
        num_heads: 8
        embeddings:
            embedding_dim: 512
            scale: True
        # typically ff_size = 4 x hidden_size
        hidden_size: 512
        ff_size: 2048
        dropout: 0.3
